version: '3'
services:
  www:
    build: ./config/php
    ports:
      - '80:80'
    volumes:
      - './htdocs:/var/www/html'
    depends_on:
      - mariadb
  mariadb:
    image: 'mariadb'
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  myadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    external_links:
      - mariadb:db
